/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grao_integration_GraoImpl */

#ifndef _Included_grao_integration_GraoImpl
#define _Included_grao_integration_GraoImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grao_integration_GraoImpl
 * Method:    getPersonInfo
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_grao_integration_GraoImpl_getPersonInfo
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    initializeCom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_initializeCom
  (JNIEnv *, jobject);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    unInitializeCom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_unInitializeCom
  (JNIEnv *, jobject);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    showConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_showConsole
  (JNIEnv *, jobject);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    setFlags
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_setFlags
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
