/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grao_integration_GraoImpl */

#ifndef _Included_grao_integration_GraoImpl
#define _Included_grao_integration_GraoImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grao_integration_GraoImpl
 * Method:    getPersonInfo
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */

//transforms methods from instance to class static methods 
//if JAVA_CLASSS_STATIC_METHODS is defined
#define JAVA_CLASSS_STATIC_METHODS

#ifdef JAVA_CLASSS_STATIC_METHODS
#define CLASS_OBJECT jclass

#else
#define CLASS_OBJECT jobject
#endif

JNIEXPORT jstring JNICALL Java_grao_integration_GraoImpl_getPersonInfo
  (JNIEnv *, CLASS_OBJECT, jstring, jlong);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    initializeCom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_initializeCom
  (JNIEnv *, CLASS_OBJECT);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    unInitializeCom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_unInitializeCom
  (JNIEnv *, CLASS_OBJECT);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    showConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_showConsole
  (JNIEnv *, CLASS_OBJECT);

/*
 * Class:     grao_integration_GraoImpl
 * Method:    setFlags
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_grao_integration_GraoImpl_setFlags
	(JNIEnv *, CLASS_OBJECT, jlong);

#ifdef __cplusplus
}
#endif
#endif
